src/objects/Asset_Acknowledgement_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Acknowledgement_Date__c</fullName>
        <label>Last Visited Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Data_Asset__c</fullName>
        <label>Data Asset</label>
        <referenceTo>RWE_Data_Asset__c</referenceTo>
        <relationshipLabel>Authorized User Tracker</relationshipLabel>
        <relationshipName>Authorized_User_Tracker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Authorized_User_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Authorized User Tracker</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Tracker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorized User Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RWE_Data_Asset__c.object
<CustomObject>
    <description>RWE Data Assets</description>
    <label>RWE Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Data Assets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Poc_DataAcknowledge.cls
public without sharing class Poc_DataAcknowledge{

    RWE_Data_Asset__c oAsset;
    list<Asset_Acknowledgement_Tracker__c> listAcknowledge = new list<Asset_Acknowledgement_Tracker__c>();
    Public string sFireWallMessage {get;private set;}
    Public Boolean IsRestrict;

    public Poc_DataAcknowledge(ApexPages.StandardController controller) {
        oAsset = (RWE_Data_Asset__c )controller.getRecord();
        listAcknowledge = [SELECT Id FROM Asset_Acknowledgement_Tracker__c WHERE Data_Asset__c =: oAsset.Id AND User__c =: UserInfo.getUserId()];
        
        sFireWallMessage  = Label.Acknowledgement;
    }
    
    public PageReference onPageLoad(){
        
        PageReference pageRef;
        if(listAcknowledge.size()>0){
            pageRef = new PageReference('/' + oAsset.Id);
            return pageRef;
        }
        else{
            return null;
        }
    }
    
    public PageReference onCancel(){
        
        PageReference pageRef = new PageReference('/apex/DataAssets');
        return pageRef;
        
    }
    
    public PageReference onAcknowledge(){
        
        Asset_Acknowledgement_Tracker__c createAcknowledge = new Asset_Acknowledgement_Tracker__c (
                                                                                                    Data_Asset__c = oAsset.Id,
                                                                                                    User__c = userInfo.getUserId(),
                                                                                                    Acknowledgement_Date__c = system.Today()
                                                                                                    );
        Database.Insert(createAcknowledge);    
        PageReference pageRef = new PageReference('/' + oAsset.Id);
        return pageRef;
        
    }
}