src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Id__c</fullName>
        <description>This field is to store the User Record id of all the users (contacts)</description>
        <label>User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <description>This will copy the user name from User object</description>
        <label>User Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check field to make a user active or inactive</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Id__c</fullName>
        <description>This is a user Id generated for every User</description>
        <displayFormat>UID-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>User Id</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UserTriggerHandler.cls
public with sharing class UserTriggerHandler {
    
    public static void OnAfterInsert(List <User> userListNew){		
		    Contact newContact = new Contact();
        
        List <Contact> toInsertContacts = new List <Contact>();
        for(User eachUser : userListNew){
            system.debug('@@ Audit Fields @@ ' + eachUser.CreatedDate);
            newContact = new Contact (	FirstName	=	eachUser.FirstName,
                                    	  LastName	=	eachUser.LastName,
                                      	Email		=	eachUser.Email,
                                     	  User_Name__c=	eachUser.Username,
                                      	Title		=	eachUser.Title,
                                      	Department	=	eachUser.Department,
                                      	Phone		=	eachUser.Phone,
                                      	MobilePhone	= 	eachUser.MobilePhone,
                                      	isActive__c =	eachUser.IsActive,
                                      	User_Id__c 	= 	eachUser.Id
                                      	//MailingAddress= eachUser.Address
                                      	);
            
            toInsertContacts.add(newContact);     
        }
            insert toInsertContacts;   
        } 
    //}
    
    /* public static void OnAfterUpdate(List <User> userListUpdate){
      List <Contact> toUpdateContact = new List <Contact>();
      for(User eachUser : userListUpdate){
           Contact getContact = [SELECT Id FROM Contact WHERE User_Id__c = :eachUser.Id];
            if(getContact.size() > 0){
                getContact.FirstName = eachUser.FirstName;
                getContact.LastName = eachUser.LastName;
                    getContact.Email =	eachUser.Email;
                    getContact.User_Name__c = eachUser.Username;
                    getContact.Title =	eachUser.Title;
                    getContact.Department =	eachUser.Department;
                    getContact.Phone =	eachUser.Phone;
                    getContact.MobilePhone = eachUser.MobilePhone;
                    getContact.isActive__c = eachUser.IsActive;
                    getContact.User_Id__c = eachUser.Id;
                    //getContact.MailingAddress= eachUser.Address;
                    }
          	else{
            	  getContact = null;
          	}
          Update getContact;
    	}
	} */
}