src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Name__c</fullName>
        <description>This will copy the user name from User object</description>
        <label>User Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check field to make a user active or inactive</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ContactTriggerHandler.cls
public with sharing class ContactTriggerHandler {
 /*   private boolean m_isExecuting = false;
	private integer BatchSize = 0;

    public ContactTriggerHandler(boolean isExecuting, integer size){
		m_isExecuting = isExecuting;
		BatchSize = size;
	}
    
    public void OnAfterInsert(Contact[] newContacts){
        User U = new User();
        for(Contact newContact : newContacts){
            U.FirstName = newContact.FirstName;
            U.LastName = newContact.LastName;
            U.Email = newContact.Email;
            U.Username = newContact.User_Name__c;
            U.CommunityNickname = newContact.FirstName;
            U.Alias = newContact.FirstName;
            U.IsActive = newContact.isActive__c;
            U.TimeZoneSidKey = newContact.TimeZone__c;
            
            
            
	}
    
    
*/    

}