src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RWE_Data_Asset__c.object
<CustomObject>
    <description>RWE Data Assets</description>
    <fields>
        <fullName>Claims_Type__c</fullName>
        <label>Claims Type</label>
        <picklist>
            <picklistValues>
                <fullName>Medicare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government (OUS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pharmacy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Data_Asset_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Asset Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RWE Data Assets</relationshipLabel>
        <relationshipName>RWE_Data_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative Claims Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Medical Records (EMR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chart Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Enrollment__c</fullName>
        <label>Enrollment</label>
        <picklist>
            <picklistValues>
                <fullName>1 - 10K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10001 - 100K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100001 - 1M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1M - 2M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2M - 5M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5M - 10M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10M - 25M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt; 25M</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Raw_Data_Accessibility__c</fullName>
        <label>Raw Data Accessibility</label>
        <picklist>
            <picklistValues>
                <fullName>Externally Accessible via Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Externally Hosted - Vendor Directly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Externally Hosted - Vendor via Data Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Externally Hosted - Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner - Analysis by Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Institution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theraputic_Area__c</fullName>
        <description>This is a list of the therapeutic areas</description>
        <label>Therapeutic Area</label>
        <picklist>
            <picklistValues>
                <fullName>Cardio Metabolic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respiratory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neuroscience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunology and Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cell and Gene Therapy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RWE Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Data Assets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RWE_Data_Asset_Approval__c.object
<CustomObject>
    <description>It will be used to invoke Approval Processes with different User for each Data Asset Record</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Legal Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending License Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RWE_Data_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RWE Data Asset</label>
        <referenceTo>RWE_Data_Asset__c</referenceTo>
        <relationshipLabel>RWE Data Asset Approvals</relationshipLabel>
        <relationshipName>RWE_Data_Asset_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relevant_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relevant Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RWE Data Asset Approvals</relationshipLabel>
        <relationshipName>RWE_Data_Asset_Approvals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RWE Request</label>
    <nameField>
        <label>RWE Data Asset Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RWE_Data_Profiler__c.object
<CustomObject>
    <description>This is a master object for profiling multiple data asset</description>
    <fields>
        <fullName>Data_Profiler_Link__c</fullName>
        <label>Data Profiler Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Data_Profiler__c</fullName>
        <label>Data Profiler Type</label>
        <picklist>
            <picklistValues>
                <fullName>Achilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>i2b2 Passport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incidence &amp; Prevalence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RWE_Data_Asset_Profiler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RWE Data Asset</label>
        <referenceTo>RWE_Data_Asset__c</referenceTo>
        <relationshipLabel>RWE Data Profilers</relationshipLabel>
        <relationshipName>RWE_Data_Profilers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RWE Data Profiler</label>
    <nameField>
        <displayFormat>DPN-{0000}</displayFormat>
        <label>Data Profiler Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWE Data Profilers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RWE_Study__c.object
<CustomObject>
    <description>It is used to group RWE Data Assets for common quality of study</description>
    <fields>
        <fullName>Research_Trials__c</fullName>
        <label>Research Trials</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Clinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Study_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Lead</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RWE Studies</relationshipLabel>
        <relationshipName>RWE_Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Pick__c</fullName>
        <label>Study Pick</label>
        <picklist>
            <picklistValues>
                <fullName>Utilized</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Produced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Study_Status__c</fullName>
        <label>Study Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Therapeutic_Area__c</fullName>
        <label>Therapeutic Area</label>
        <picklist>
            <picklistValues>
                <fullName>Cardio Metabolic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respiratory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neuroscience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunology and Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cell and Gene Therapy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RWE Study</label>
    <nameField>
        <label>RWE Study Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {

    public static Contact createContact(){
        Contact con = new Contact(  FirstName = 'TestFirst',
                                    LastName = 'TestLast',
                                    Email = 'test@test.com',
                                    Related_User__c = UserInfo.getUserId()
                                    );
        return con;
    }
    
    public static RWE_Data_Asset__c  createDataAsset(String contactId) { 
        RWE_Data_Asset__c  dataAsset = new RWE_Data_Asset__c ( Name = 'Test Data Asset',
                                                                Raw_Data_Accessibility__c = 'Test Accessibiltiy',
                                                                Theraputic_Area__c = 'Test Theraputic Area',
                                                                Claims_Type__c = 'Test Claim Type',
                                                                Data_Type__c = 'Test Data Type',
                                                                Enrollment__c = '100-200',
                                                                Data_Asset_Owner__c = contactId
                                                                );  
                        
        
        return dataAsset;
    }

    public static RWE_Data_Profiler__c createDataProfiler(string dataAssetId){
        RWE_Data_Profiler__c dataProfiler = new RWE_Data_Profiler__c(   Data_Profiler__c = 'Test Proifler',
                                                                        Data_Profiler_Link__c = 'www.test.com',
                                                                        RWE_Data_Asset_Profiler__c = dataAssetId);
        return dataProfiler;                                                                        
    }
    
    public static RWE_Study__c createStudy(string contactId){
        RWE_Study__c study = new RWE_Study__c(   Study_Lead__c = contactId,
                                                        Name = 'TestStudy',
                                                        Research_Trials__c = 'Test Trial',
                                                        Study_Pick__c = 'Test Pick',
                                                        Study_Status__c = 'In Progress',
                                                        Therapeutic_Area__c = 'Test Generic');
        return study;                                                                        
    }
    
    public static RWE_Data_Asset_Approval__c createRequest(string dataAssetId, string contactId){
        RWE_Data_Asset_Approval__c request = new RWE_Data_Asset_Approval__c(   Approval_Status__c= 'Approved',
                                                        Relevant_Contact__c = contactId,
                                                        Requestor__c = UserInfo.getUserId(),
                                                        RWE_Data_Asset__c = dataAssetId);
        return request;                                                                        
    }
    
          
}