src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Arrived_Request__c</fullName>
        <label>Last Arrived Request</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RWE_Data_Asset_Approval__c.object
<CustomObject>
    <description>It will be used to invoke Approval Processes with different User for each Data Asset Record</description>
    <fields>
        <fullName>Relevant_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relevant Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RWE Data Asset Approvals</relationshipLabel>
        <relationshipName>RWE_Data_Asset_Approvals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>RWE Request</label>
    <nameField>
        <label>RWE Data Asset Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NavigationController.cls
/***************************************************************************************************************************************** 
 * Class Name   : NavigationController 
 * Description  : Data Assest Records will be displayed based on Selected Criteria
 * Created By   : 
 * 
 *****************************************************************************************************************************************/
Public class NavigationController
{
    Public string sRequsestCount
    {
        get;
        set;
    }
    public NavigationController()
    {
        system.debug('To Check');
        List<Contact> cLastArrivalDate = [SELECT Id, Last_Arrived_Request__c FROM Contact WHERE Related_User__c =:  UserInfo.getUserId()];
        Datetime stringDate;
        if(cLastArrivalDate.size() > 0 ){
            stringDate = cLastArrivalDate[0].Last_Arrived_Request__c;
        }
        if(stringDate != null){
            AggregateResult ar = [SELECT count(Id) gCount FROM RWE_Data_Asset_Approval__c WHERE Relevant_Contact__r.Related_User__c =: UserInfo.getUserId() AND LastModifiedDate >: stringDate];
            sRequsestCount = (String) ar.get('gCount');
        }
        
    }
    
    public void qUpdateRequest()
    {
        Contact qUpdateContact = [SELECT Id, Last_Arrived_Request__c FROM Contact WHERE Related_User__c =: UserInfo.getUserId()];
        qUpdateContact.Last_Arrived_Request__c = system.Now();
        system.debug('@@ qUpdateContact @@' + qUpdateContact);
        update qUpdateContact;
    }
}