src/objects/Junction_Data_Asset_Study__c.object
<CustomObject>
    <description>This is a junction object for RWE Study and RWE Data Asset</description>
    <fields>
        <fullName>RWE_Data_Asset__c</fullName>
        <label>RWE Data Asset</label>
        <referenceTo>RWE_Data_Asset__c</referenceTo>
        <relationshipLabel>RWE Data Asset - Study Link</relationshipLabel>
        <relationshipName>RWE_Data_Asset_Study_Link</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RWE_Study__c</fullName>
        <label>RWE Study</label>
        <referenceTo>RWE_Study__c</referenceTo>
        <relationshipLabel>RWE Data Asset - Study Link</relationshipLabel>
        <relationshipName>RWE_Data_Asset_Study_Link</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RWE Data Asset - Study Link</label>
    <nameField>
        <displayFormat>RWE-DAS-{00000}</displayFormat>
        <label>Data Asset - Study ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWE Data Asset - Study Link</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RWE_Data_Asset__c.object
<CustomObject>
    <description>RWE Data Assets</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global [Multiple Regions]</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unspecified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RWE Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Data Assets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RWE_Study__c.object
<CustomObject>
    <description>It is used to group RWE Data Assets for common quality of study</description>
    <fields>
        <fullName>Count_Study_Link__c</fullName>
        <label>Count Study Link</label>
        <summaryForeignKey>Junction_Data_Asset_Study__c.RWE_Study__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global [Multiple Regions]</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unspecified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This is a study start date.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Study_Description__c</fullName>
        <label>Study Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Study_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Lead</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RWE Studies</relationshipLabel>
        <relationshipName>RWE_Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Pick__c</fullName>
        <label>Study Pick</label>
        <picklist>
            <picklistValues>
                <fullName>Utilized</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Produced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Study_Status__c</fullName>
        <label>Study Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Study_Type__c</fullName>
        <label>Study Type</label>
        <picklist>
            <picklistValues>
                <fullName>Meta-Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modeling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observational Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pragmatic Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systematic Literature Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Therapeutic_Area__c</fullName>
        <label>Therapeutic Area</label>
        <picklist>
            <picklistValues>
                <fullName>Cardio Metabolic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respiratory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neuroscience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunology and Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cell and Gene Therapy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RWE Study</label>
    <nameField>
        <label>RWE Study Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StudyListController.cls
/*
 * @Class Name   : StudyListController 
 * @Description  : Data Assest Records will be displayed based on Selected Criteria
 */

Public class StudyListController
{
    Public ApexPages.StandardSetController cStudyListCntlr {get;set;}
    
    Public Map < String, Integer > mCategoyCount {get;set;}
     
    Public Map < String, List < WrapperLabelCheckBox >> mStudyObjectStructure {get;set;}
    
    /* 
     * @Method Name                    :  getStudies
     * @Description                    :  Initialize cStudyListCntlr and return a list of records
     */
    
    Public List < RWE_Study__c > getStudies()
    {
        return (List < RWE_Study__c > ) cStudyListCntlr.getRecords();
    }

    //Constructor
    Public StudyListController(ApexPages.StandardController controller)
    {
        // Initialization
        mStudyObjectStructure = new Map < String, List < WrapperLabelCheckBox >> ();

        // Methods called
        DescribeObjectWithDetails();
        Query();
    }

    /* 
     * @Method Name                    :  DescribeObjectWithDetails
     * @Description                    :  This method populates the filtering fields on the UI page 
     */
    
    Public Void DescribeObjectWithDetails()
    {
        List < WrapperLabelCheckBox > lPicklist = new List < WrapperLabelCheckBox > ();
        mCategoyCount = new Map < String, Integer > ();

        for (Schema.Picklistentry oPicklistValues: RWE_Study__c.Therapeutic_Area__c.getDescribe().getPicklistValues())
        {
            lPicklist.add(new WrapperLabelCheckBox(oPicklistValues.Value, false));
            mCategoyCount.put(oPicklistValues.Label, 0);
        }
        mStudyObjectStructure.put('Therapeutic_Area__c', lPicklist);

        lPicklist = new List < WrapperLabelCheckBox > ();
        for (Schema.Picklistentry oPicklistValues: RWE_Study__c.Study_Type__c.getDescribe().getPicklistValues())
        {
            lPicklist.add(new WrapperLabelCheckBox(oPicklistValues.Value, false));
            mCategoyCount.put(oPicklistValues.Label, 0);
        }
        mStudyObjectStructure.put('Study_Type__c', lPicklist);

        lPicklist = new List < WrapperLabelCheckBox > ();
        for (Schema.Picklistentry oPicklistValues: RWE_Study__c.Study_Status__c.getDescribe().getPicklistValues())
        {
            lPicklist.add(new WrapperLabelCheckBox(oPicklistValues.Value, false));
            mCategoyCount.put(oPicklistValues.Label, 0);
        }
        mStudyObjectStructure.put('Study_Status__c', lPicklist);
        
        lPicklist = new List < WrapperLabelCheckBox > ();
        for (Schema.Picklistentry oPicklistValues: RWE_Study__c.Region__c.getDescribe().getPicklistValues())
        {
            lPicklist.add(new WrapperLabelCheckBox(oPicklistValues.Value, false));
            mCategoyCount.put(oPicklistValues.Label, 0);
        }
        mStudyObjectStructure.put('Region__c', lPicklist);
        
        
        for (String mCount: mCategoyCount.keyset())
        {
            mCategoyCount.put(mCount, 0);
        }
        
        string sCombineQueryString =  HomePageUtility.cAggregateQueryString('Therapeutic_Area__c', 'RWE_Study__c' );
        
        system.debug('@@ sCombineQueryString @@ ' + sCombineQueryString);
            
        for (AggregateResult ar: database.query(sCombineQueryString))
        {
            mCategoyCount.put((String) ar.get('Therapeutic_Area__c'), (Integer) ar.get('gCount'));
        }
        
        sCombineQueryString =  HomePageUtility.cAggregateQueryString('Study_Status__c', 'RWE_Study__c');

        for (AggregateResult ar: database.query(sCombineQueryString))
        {
            mCategoyCount.put((String) ar.get('Study_Status__c'), (Integer) ar.get('gCount'));
        }
        
        sCombineQueryString =  HomePageUtility.cAggregateQueryString('Study_Type__c', 'RWE_Study__c');

        for (AggregateResult ar: database.query(sCombineQueryString))
        {
            mCategoyCount.put((String) ar.get('Study_Type__c'), (Integer) ar.get('gCount'));
        }
        
        sCombineQueryString =  HomePageUtility.cAggregateQueryString('Region__c', 'RWE_Study__c');
        for (AggregateResult ar: database.query(sCombineQueryString))
        {
            mCategoyCount.put((String) ar.get('Region__c'), (Integer) ar.get('gCount'));
        }
    }
    

    /* 
     * @Method Name                    :  Query
     * @Description                    :  This method queries the data base and displays the results on UI
     */
    
    Public void Query()
    {
        String sRegionClause = '';
        String sAccessMethodClause = '';
        String sTherapeuticAreaClause = '';
        String sRegionMethodClause= '';


        sRegionClause = HomePageUtility.FrameClause(mStudyObjectStructure.get('Study_Type__c'));
        if (sRegionClause != '')
        {
            sRegionClause = ' Study_Type__c IN ' + sRegionClause;
        }

        sTherapeuticAreaClause = HomePageUtility.FrameClause(mStudyObjectStructure.get('Therapeutic_Area__c'));
        if (sTherapeuticAreaClause != '')
        {
            sTherapeuticAreaClause = ' Therapeutic_Area__c IN ' + sTherapeuticAreaClause;
        }
        
        sRegionMethodClause= HomePageUtility.FrameClause(mStudyObjectStructure.get('Region__c'));
        if (sRegionMethodClause!= '')
        {
            sRegionMethodClause= ' Region__c IN ' + sRegionMethodClause;
        }


        sAccessMethodClause = HomePageUtility.FrameClause(mStudyObjectStructure.get('Study_Status__c'));
        if (sAccessMethodClause != '')
        {
            sAccessMethodClause = ' Study_Status__c IN ' + sAccessMethodClause;
        }

        cStudyListCntlr = new ApexPages.StandardSetController(Database.getQueryLocator(
            'SELECT Name,Owner.Name,createddate,Start_Date__c,Study_Type__c,Therapeutic_Area__c,Study_Status__c,Study_Pick__c,Count_Study_Link__c,Study_Description__c,Study_Lead__c,Study_Lead__r.Name,  (Select Id, RWE_Data_Asset__c From RWE_Data_Asset_Study_Link__r)   FROM RWE_Study__c ' + HomePageUtility.CombineQuery('WHERE', new List < String >
            {                // , (SELECT Id, Name FROM Junction_Data_Asset_Studys__r)
                sRegionClause, sAccessMethodClause, sTherapeuticAreaClause, sRegionMethodClause
            }) + ' ORDER BY Name ASC NULLS FIRST' ));
        // cStudyListCntlr.setPageSize(10000);     
    }

    /* 
     * @Method Name                    :  FetchDataForCriteria
     * @Description                    :  This method is called upon anny action on UI to query the data base
     */
    
    public void FetchDataForCriteria()
    {
        Query();
    }
}