src/objects/RWE_Data_Asset__c.object
<CustomObject>
    <description>RWE Data Assets</description>
    <fields>
        <fullName>Claims_Type__c</fullName>
        <label>Claims Type</label>
        <picklist>
            <picklistValues>
                <fullName>Medicare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government (OUS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pharmacy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Count_Studies__c</fullName>
        <label>Count Studies</label>
        <summaryForeignKey>Junction_Data_Asset_Study__c.RWE_Data_Asset__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Create_Cohort__c</fullName>
        <label>Create Cohort</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Asset_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Asset Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RWE Data Assets</relationshipLabel>
        <relationshipName>RWE_Data_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative Claims Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Medical Records (EMR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chart Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Enrollment__c</fullName>
        <label>Enrollment</label>
        <picklist>
            <picklistValues>
                <fullName>1 - 10K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10001 - 100K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100001 - 1M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1M - 2M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2M - 5M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5M - 10M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10M - 25M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt; 25M</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Open_Cohort__c</fullName>
        <label>Open Cohort</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Raw_Data_Accessibility__c</fullName>
        <label>Raw Data Accessibility</label>
        <picklist>
            <picklistValues>
                <fullName>Externally Accessible via Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Externally Hosted - Vendor Directly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Externally Hosted - Vendor via Data Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Externally Hosted - Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner - Analysis by Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Institution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global [Multiple Regions]</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unspecified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theraputic_Area__c</fullName>
        <description>This is a list of the therapeutic areas</description>
        <label>Therapeutic Area</label>
        <picklist>
            <picklistValues>
                <fullName>Cardio Metabolic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respiratory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neuroscience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunology and Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cell and Gene Therapy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RWE Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Data Assets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RWE_Data_Profiler__c.object
<CustomObject>
    <description>This is a master object for profiling multiple data asset</description>
    <fields>
        <fullName>Data_Profiler_Link__c</fullName>
        <label>Data Profiler Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Data_Profiler__c</fullName>
        <label>Data Profiler Type</label>
        <picklist>
            <picklistValues>
                <fullName>Achilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>i2b2 Passport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incidence &amp; Prevalence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RWE_Data_Asset_Profiler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RWE Data Asset</label>
        <referenceTo>RWE_Data_Asset__c</referenceTo>
        <relationshipLabel>RWE Data Profilers</relationshipLabel>
        <relationshipName>RWE_Data_Profilers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RWE Data Profiler</label>
    <nameField>
        <displayFormat>DPN-{0000}</displayFormat>
        <label>Data Profiler Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWE Data Profilers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DataAssetController.cls
/*
 * @Class Name   : DataAssetController 
 * @Description  : Data Assest Records will be displayed based on Selected Criteria
 */

Public class DataAssetController
{
    Public List < RWE_Data_Asset__c > cDataAssetListCntlr {get;set;}
    
    Public Map < String, Integer > mCategoyCount {get;set;}
     
    Public Map < String, List < WrapperLabelCheckBox >> mDataAssetObjectStructure {get;set;}
    

    //Cnstructor
    Public DataAssetController(ApexPages.StandardController controller)
    {
        // Initialization
        mDataAssetObjectStructure = new Map < String, List < WrapperLabelCheckBox >> ();

        // Methods called
        DescribeObjectWithDetails();
        Query();
    }

    /* 
     * @Method Name                    :  DescribeObjectWithDetails
     * @Description                    :  This method populates the filtering fields on the UI page 
     */
    
    Public Void DescribeObjectWithDetails()
    {
        List < WrapperLabelCheckBox > lPicklist = new List < WrapperLabelCheckBox > ();
        mCategoyCount = new Map < String, Integer > ();

        for (Schema.Picklistentry oPicklistValues: RWE_Data_Asset__c.Theraputic_Area__c.getDescribe().getPicklistValues())
        {
            lPicklist.add(new WrapperLabelCheckBox(oPicklistValues.Value, false));
            mCategoyCount.put(oPicklistValues.Label, 0);
        }
        mDataAssetObjectStructure.put('Theraputic_Area__c', lPicklist);

        lPicklist = new List < WrapperLabelCheckBox > ();
        for (Schema.Picklistentry oPicklistValues: RWE_Data_Asset__c.Raw_Data_Accessibility__c.getDescribe().getPicklistValues())
        {
            lPicklist.add(new WrapperLabelCheckBox(oPicklistValues.Value, false));
            mCategoyCount.put(oPicklistValues.Label, 0);
        }
        mDataAssetObjectStructure.put('Raw_Data_Accessibility__c', lPicklist);

        lPicklist = new List < WrapperLabelCheckBox > ();
        for (Schema.Picklistentry oPicklistValues: RWE_Data_Asset__c.Data_Type__c.getDescribe().getPicklistValues())
        {
            lPicklist.add(new WrapperLabelCheckBox(oPicklistValues.Value, false));
            mCategoyCount.put(oPicklistValues.Label, 0);
        }
        mDataAssetObjectStructure.put('Data_Type__c', lPicklist);
        
        lPicklist = new List < WrapperLabelCheckBox > ();
        for (Schema.Picklistentry oPicklistValues: RWE_Data_Asset__c.Region__c.getDescribe().getPicklistValues())
        {
            lPicklist.add(new WrapperLabelCheckBox(oPicklistValues.Value, false));
            mCategoyCount.put(oPicklistValues.Label, 0);
        }
        mDataAssetObjectStructure.put('Region__c', lPicklist);
        
        
        for (String mCount: mCategoyCount.keyset())
        {
            mCategoyCount.put(mCount, 0);
        }
        
        string sCombineQueryString =  HomePageUtility.cAggregateQueryString('Theraputic_Area__c', 'RWE_Data_Asset__c' );
        
        system.debug('@@ sCombineQueryString @@ ' + sCombineQueryString);
            
        for (AggregateResult ar: database.query(sCombineQueryString))
        {
            mCategoyCount.put((String) ar.get('Theraputic_Area__c'), (Integer) ar.get('gCount'));
        }
        
        sCombineQueryString =  HomePageUtility.cAggregateQueryString('Data_Type__c', 'RWE_Data_Asset__c');

        for (AggregateResult ar: database.query(sCombineQueryString))
        {
            mCategoyCount.put((String) ar.get('Data_Type__c'), (Integer) ar.get('gCount'));
        }
        
        sCombineQueryString =  HomePageUtility.cAggregateQueryString('Raw_Data_Accessibility__c', 'RWE_Data_Asset__c');

        for (AggregateResult ar: database.query(sCombineQueryString))
        {
            mCategoyCount.put((String) ar.get('Raw_Data_Accessibility__c'), (Integer) ar.get('gCount'));
        }
        
        sCombineQueryString =  HomePageUtility.cAggregateQueryString('Region__c', 'RWE_Data_Asset__c');

        for (AggregateResult ar: database.query(sCombineQueryString))
        {
            mCategoyCount.put((String) ar.get('Region__c'), (Integer) ar.get('gCount'));
        }
    }

    /* 
     * @Method Name                    :  Query
     * @Description                    :  This method queries the data base and displays the results on UI 
     * @Return Type                    :  void
     * @Parameters                     :  String sOrder
     */
    
    Public void Query()
    {
        String sRegionClause = '';
        String sAccessMethodClause = '';
        String sTherapeuticAreaClause = '';
        String sRegionMethod = '';

        sRegionClause = HomePageUtility.FrameClause(mDataAssetObjectStructure.get('Raw_Data_Accessibility__c'));
        if (sRegionClause != '')
        {
            sRegionClause = ' Raw_Data_Accessibility__c IN ' + sRegionClause;
        }

        sTherapeuticAreaClause = HomePageUtility.FrameClause(mDataAssetObjectStructure.get('Theraputic_Area__c'));
        if (sTherapeuticAreaClause != '')
        {
            sTherapeuticAreaClause = ' Theraputic_Area__c IN ' + sTherapeuticAreaClause;
        }
        
        sRegionMethod = HomePageUtility.FrameClause(mDataAssetObjectStructure.get('Region__c'));
        if (sRegionMethod != '')
        {
           sRegionMethod = ' Region__c IN ' + sRegionMethod ;
        }


        sAccessMethodClause = HomePageUtility.FrameClause(mDataAssetObjectStructure.get('Data_Type__c'));
        if (sAccessMethodClause != '')
        {
            sAccessMethodClause = ' Data_Type__c IN ' + sAccessMethodClause;
        }

        cDataAssetListCntlr = Database.Query(
            'SELECT Name,Owner.Name,CreatedDate,Raw_Data_Accessibility__c,Theraputic_Area__c,Data_Asset_Owner__r.Name,Data_Asset_Owner__c,Description__c,Claims_Type__c,Created_Date__c,Data_Type__c,Enrollment__c, Open_Cohort__c, Create_Cohort__c, Count_Studies__c,  (SELECT Id,Data_Profiler__c, Data_Profiler_Link__c FROM RWE_Data_Profilers__r) FROM RWE_Data_Asset__c ' + HomePageUtility.CombineQuery('WHERE', new List < String >
            {
                sRegionClause, sAccessMethodClause, sTherapeuticAreaClause, sRegionMethod 
            }) + ' ORDER BY Name ASC NULLS FIRST' );
            
            // system.debug('@@ SOMETHING   @@' + cDataAssetListCntlr.getResultSize() );
    }

    /* 
     * @Method Name                    :  FetchDataForCriteria
     * @Description                    :  This method is called upon anny action on UI to query the data base
     */
    
    public void FetchDataForCriteria()
    {
        system.debug('inside controller');
        Query();
    }
}