src/objects/RWE_Data_Asset__c.object
<CustomObject>
    <description>RWE Data Assets</description>
    <label>RWE Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Data Assets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RWE_Data_Asset_Approval__c.object
<CustomObject>
    <description>It will be used to invoke Approval Processes with different User for each Data Asset Record</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Legal Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending License Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RWE_Data_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RWE Data Asset</label>
        <referenceTo>RWE_Data_Asset__c</referenceTo>
        <relationshipLabel>RWE Data Asset Approvals</relationshipLabel>
        <relationshipName>RWE_Data_Asset_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RWE Request</label>
    <nameField>
        <label>RWE Data Asset Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RWE_Partnership__c.object
<CustomObject>
    <description>This is object is used to track and manage partnerships</description>
    <label>RWE Partnership</label>
    <nameField>
        <label>RWE Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RWE_Study__c.object
<CustomObject>
    <description>It is used to group RWE Data Assets for common quality of study</description>
    <label>RWE Study</label>
    <nameField>
        <label>RWE Study Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HomePage.cls
/****************************************************************************************************************************************** 
* Class Name   : HomePage
* Description  : Class for the HomePage on the UI
* Created By   : AJ
* 
*****************************************************************************************************************************************/
public with sharing class HomePage {

    public String getA() {
        return null;
    }
    
    public string cLegalUserProfileId = DataAssetApprovalRejectionExtension.gProfileId('Legal Reviewer');
    public string cLicenseUserProfileId = DataAssetApprovalRejectionExtension.gProfileId('License Reviewer');
    public string cSystemAdminProfileId = DataAssetApprovalRejectionExtension.gProfileId('System Administrator');
    string aWhereCondition = '' ;

    Public Map<String,Integer> mCategoyCount {get;set;} 

        //Loading the Constructor
    public HomePage () {
            
        mCategoyCount = new Map<String,Integer>();
        
        
        if(UserInfo.getProfileId() == cLegalUserProfileId )
        {
            aWhereCondition += ' Approval_Status__c = \'Pending License Approval\'';
        }
        else if(UserInfo.getProfileId() == cLicenseUserProfileId)
        {
            aWhereCondition += ' Approval_Status__c = \'Pending Legal Approval\'';
        }
        else if( UserInfo.getProfileId() == cSystemAdminProfileId)
        {
            aWhereCondition += ' (Approval_Status__c = \'Pending Legal Approval\' OR Approval_Status__c = \'Pending License Approval\')' ;
        }
        else
        {
            Id userId = UserInfo.getUserId();
            aWhereCondition += ' Requestor__c =:  userId ';
        }
        
        system.debug(' @@ aWhereCondition   @@ ' + aWhereCondition );
        
        for (AggregateResult ar : database.query('SELECT count(Id) FROM RWE_Data_Asset_Approval__c WHERE '  + aWhereCondition)) {
            mCategoyCount.put('Request',(Integer)ar.get('expr0'));
        }
        
        for (AggregateResult ar : [SELECT count(Id) FROM RWE_Partnership__c]) {
            mCategoyCount.put('Partnerships',(Integer)ar.get('expr0'));
        }
                
        for (AggregateResult ar : [SELECT count(Id) FROM RWE_Data_Asset__c]) {
            mCategoyCount.put('DataAssets',(Integer)ar.get('expr0'));
        }
        
        
        for (AggregateResult ar : [SELECT count(Id) FROM RWE_Study__c]) {
            mCategoyCount.put('Study',(Integer)ar.get('expr0'));
        }      
         
    }
}