src/objects/RWE_Data_Asset__c.object
<CustomObject>
    <description>RWE Data Assets</description>
    <label>RWE Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Data Assets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RWE_Data_Asset_Approval__c.object
<CustomObject>
    <description>It will be used to invoke Approval Processes with different User for each Data Asset Record</description>
    <fields>
        <fullName>RWE_Data_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RWE Data Asset</label>
        <referenceTo>RWE_Data_Asset__c</referenceTo>
        <relationshipLabel>RWE Data Asset Approvals</relationshipLabel>
        <relationshipName>RWE_Data_Asset_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relevant_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relevant Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RWE Data Asset Approvals</relationshipLabel>
        <relationshipName>RWE_Data_Asset_Approvals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_Till__c</fullName>
        <label>Valid Till</label>
        <type>Date</type>
    </fields>
    <label>RWE Request</label>
    <nameField>
        <label>RWE Data Asset Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RWE_Data_Profiler__c.object
<CustomObject>
    <description>This is a master object for profiling multiple data asset</description>
    <label>RWE Data Profiler</label>
    <nameField>
        <displayFormat>DPN-{0000}</displayFormat>
        <label>Data Profiler Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWE Data Profilers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RWE_Study__c.object
<CustomObject>
    <description>It is used to group RWE Data Assets for common quality of study</description>
    <label>RWE Study</label>
    <nameField>
        <label>RWE Study Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DataAssetControllerTest.cls
@isTest 
public class DataAssetControllerTest {
    static testMethod void dataAssetTestMethod() {
        
        Contact insertCon = TestDataFactory.createContact();
        insert insertCon;
        RWE_Data_Asset__c insertDataAsset = TestDataFactory.createDataAsset(insertCon.Id);
        insert insertDataAsset;
        RWE_Data_Profiler__c insertProfiler = TestDataFactory.createDataProfiler(insertDataAsset.Id);
        insert insertProfiler;
        RWE_Study__c insertStudy = TestDataFactory.createStudy(insertCon.Id);
        insert insertStudy;
        RWE_Data_Asset_Approval__c insertRequest = TestDataFactory.createRequest(insertDataAsset.Id, insertCon.Id);
        insert insertRequest;
		
		RWE_Data_Asset_Approval__c dataAssetApprovalRejection = new RWE_Data_Asset_Approval__c(	Name = insertDataAsset.Name,
																								Relevant_Contact__c = insertCon.Id,
																								Requestor__c = UserInfo.getUserId(),
																								RWE_Data_Asset__c = insertDataAsset.Id,
																								Valid_Till__c = Date.Today().addMonths(3));
		// insert dataAssetApprovalRejection;																						
        
        ApexPages.StandardController scDataAsset = new ApexPages.standardController(insertDataAsset);
        DataAssetController dataAssetCont = new DataAssetController(scDataAsset);
        dataAssetCont.FetchDataForCriteria();
        
        ApexPages.StandardController scStudy = new ApexPages.standardController(insertStudy);
        StudyListController studyCont = new StudyListController(scStudy);
        studyCont.FetchDataForCriteria();
		
		ApexPages.StandardController createApp = new ApexPages.standardController(dataAssetApprovalRejection);
        DataAssetApprovalCreationExtension createApproval = new DataAssetApprovalCreationExtension(createApp);
		PageReference pgRef = Page.DataAssetApprovalCreation; 
		Test.setCurrentPage(pgRef); 
		ApexPages.currentPage().getParameters().put('dataId', insertDataAsset.id);
		system.debug('@@ PageRef @@' + pgRef );
		dataAssetApprovalRejection = new RWE_Data_Asset_Approval__c();
        createApproval.iDataApprovalRecord();
		
		dataAssetApprovalRejection = [select id from RWE_Data_Asset_Approval__c limit 1];
        ApexPages.StandardController dataAssetApproRej = new ApexPages.standardController(dataAssetApprovalRejection);
        DataAssetApprovalRejectionExtension dataAssAppRej = new DataAssetApprovalRejectionExtension(dataAssetApproRej);
		dataAssAppRej.cLincenseActive  = true;
		dataAssAppRej.cLincenseUsage  = true;
		dataAssAppRej.cUserCredentials  = true;
		dataAssAppRej.cDataLicense  = true;
		dataAssAppRej.cRestriction  = true;
		dataAssAppRej.cFirstLevelApproval  = true;
		dataAssAppRej.cSecondLevelApproval  = true;
        dataAssAppRej.eApproveRequest();
		dataAssAppRej.eRejectRequest();
		


		
                
    }
}