src/objects/RWE_Data_Asset__c.object
<CustomObject>
    <description>RWE Data Assets</description>
    <fields>
        <fullName>Data_Asset_ID__c</fullName>
        <description>This is a RWE Data Asset ID unique for every record of the object.</description>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Data Asset ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Data_Continuity__c</fullName>
        <label>Data Continuity</label>
        <picklist>
            <picklistValues>
                <fullName>Longitudinal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-Sectional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative Claims Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Medical Records (EMR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chart Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Enrollment__c</fullName>
        <label>Enrollment</label>
        <picklist>
            <picklistValues>
                <fullName>1 - 10K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10001 - 100K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100001 - 1M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1M - 2M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2M - 5M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5M - 10M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10M - 25M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt; 25M</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Medical_Reports__c</fullName>
        <label>Medical Reports Availablility</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RWE Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Data Assets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ProcessDecision.cls
public with sharing class ProcessDecision {

    public String recId;
    public RWE_Data_Asset__c records {get; set;}
    
    
    public processDecision (){
        recId = ApexPages.currentPage().getParameters().get('id'); 
        records = [select Name,Data_Asset_ID__c,Data_Continuity__c,Data_Type__c,Enrollment__c,Medical_Reports__c FROM RWE_Data_Asset__c where id =:recId];
        
        
        }








}